[project]
name = "driftmon"
version = "0.1.1"
description = "Data drift detector for data"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [
    { name = "Human-Gechi", email = "okoliogechi74@gmail.com" }
]
keywords = ["data", "drift", "monitoring"]
dependencies = [
    "pandas==2.3.3",
    "scipy==1.17.1",
    "psycopg2-binary==2.9.11",
    "pytest==9.0.3",
    "google-cloud-bigquery== 3.41.0",
    "mysqlclient==2.2.8",
    "snowflake-connector-python==4.4.0",
    "google-auth==2.49.2",
    "ruff==0.15.10",
    "db-dtypes==1.5.1",
    "google-cloud-bigquery-storage==2.37.0",
    "streamlit==1.56.0",
    "numpy==2.4.4",
    "scipy==1.17.1",
    "statsmodels==0.14.6",
    "slack_sdk==3.41.0",
    "prompt_toolkit== 3.0.52",
    "typer==0.25.0",
    "plotly==6.7.0",
    "pyyaml==6.0.3",
    "numpy==2.4.4"
]

[project.optional-dependencies]
dev = [
    "ruff>=0.15.10"
]
[project.urls]
Repository = "https://github.com/Human-Gechi/data_drift_detector"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 100
target-version = "py311"

exclude = [
    ".gitignore",
    "venv"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.ruff.lint]
select = ["E", "I"]

[project.scripts]
driftmon = "driftmon.cli:main_shell"
driftmon-dashboard="driftmon.dashboard.launch_dashboard:_main"